# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z_j_MxbbeeOhg6mtD5Wz_uRcPIsvffIh
"""

import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[1, 1, 2])

import numpy as np
arr = np.array([1, 2, 3,4, 5, 6, 7,8,9,10,11,12,13])
print(arr[1:5])