# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DK1eWPR8mGjUdha6MaCHGFILAi5Nt_9m
"""

import matplotlib.pyplot as plt
data = [5, 7, 7,8,9,10,10,10,11,12,11,11]
plt.hist(data, bins = 10, edgecolor = 'black')
plt.title('Simple Histogram Example')
plt.xlabel('Value')
plt.ylabel('Count')
plt.show()
plt.ylabel('Count')
plt.show()